### ISSUE TITLE
Delete Agreement Dialog

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#104]
See [figma](https://www.figma.com/file/oTbgKEXP9kTSbSWsfOnGwp/Consenz-Wireframe?node-id=2023%3A13902)
see [zeplin](https://app.zeplin.io/project/629dca51967eeb127721428d/screen/62e9263a1fad1111764f490e)

## DOD:
- [x] A dialog for agreement deletion, with a header, content, delete and cancel buttons
- [x] On cancel, call `onCancel()` (use a prop)
- [x] Add `deleteAgreement` function (useMutation) to group context - in state
- [x] On delete, call `deleteAgreement()`, then call `onDelete()` (use a prop)

**Comment by yishain11** [comment]
is the buttons order important? the dialog I created in #98 can be used here, but the buttons arrangment at the bottom is different

**Comment by consenz** [comment]
Delete option should be shown on all agreements.
