### ISSUE TITLE
Preliminary Section Card

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#119]
[Zeplin](https://app.zeplin.io/project/629dca51967eeb127721428d/screen/62e93ecde17dc515b68abd25)
## DOD:
- [x] A card that displays section index, content of first suggestion
- [x] The section object should be passed as a prop
- [x] Add buttons (same as zeplin)
- [x] Disable back arrow (zee zeplin) when currently displayed suggestion is the first one
- [x] Disable forward arrow when currently displayed suggestion is the last one

**Comment by avirankatz** [comment]
@yishain11 is this ready for PR?

**Comment by Aharon-Porath** [comment]
@avirankatz Need to take into consideration (now or later) versions display order in section card on agreement page and on section page:

The parameter for sorting is by voting ratio - 
- The most agreed upon version, i.e. the version that it's pro voters number minus it's con voters number is the highest, should be displayed first. 
- The least agreed upon version, i.e. the version that it's pro voters number minus it's con voters number is the lowest, should be displayed last.
- For versions that have the same voting ratio, sorting should be according to creation time, descending (i.e. newest first).
- If there is an approved version, it should be positioned as first (on the left in LtR, on the right in RtL), but it should not be displayed by default. Approved version will be displayed only after user click on back arrow.

Please confirm that it is clear.

**Comment by avirankatz** [comment]
@Aharon-Porath Yes, it's clear.
However, if there's going to be some scoring field for suggestions (for the purpose of the consensus meter), won't it be useful for sorting? i.e. first suggestion is the one which has the highest score

**Comment by Aharon-Porath** [comment]
> @Aharon-Porath Yes, it's clear. However, if there's going to be some scoring field for suggestions (for the purpose of the consensus meter), wouldn't it also be useful for sorting? i.e. first suggestion is the one which has the highest score

Yes, it could be more simple.

As a general rule, the requirement for sorting/displaying suggestion (section version on a vote) is - the version that is the closest to be approved should be the most accessible to the user. 

And if I will phrase it as a user story:
As a user I want to see first the versions with the highest chances to be approved, so I can vote for the ones that I agreed with and promote them to enter the draft, and to object to the ones that I disagree with to prevent them to enter the draft.
