### ISSUE TITLE
Text editor tooltip

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#133]
## DOD:
- [x] Meeting with Aviran, after which we're going to re-estimate this issue
- [x] Append tiptap bubble menu with:
  - [x] Bullet list
  - [x] Number list
  - [ ] RTL/LTR
  - [x] Hyperlink
  - [x] Table

**Comment by biwashingtonial** [comment]
Note that we have decided to defer RTL/LTR to a later iteration. It appears to require writing a Tiptap extension and currently when the Consenz app is in RTL direction the editor does follow. The only need will be for users wishing to mix LTR and RTL languages in the same document.
