### ISSUE TITLE
Agreement page - make chapters foldable

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#151]
## DOD:
- [x] Add down arrow to the chapter's row
- [x] Make the row fold on click ([accordion](https://mui.com/material-ui/react-accordion/) component may be useful)
- [x] add design as in [zeplin](https://app.zeplin.io/project/629dca51967eeb127721428d/screen/63355d6cda2c5d9897a406e5)

**Comment by yishain11** [comment]
we need a comprehensive style for the accordion. it looks pretty bad now...

**Comment by yishain11** [comment]
@avirankatz I will look at it
