### ISSUE TITLE
Section card progress bar by threshold

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#177]
[Zeplin](https://app.zeplin.io/project/629dca51967eeb127721428d/screen/62e93ecde17dc515b68abd25)
## DOD:
- [x] Add threshold field to the agreement query -> section version object
- [x] Display a progress bar by the version's threshold
- [x] value: `Math.max(0,(upvotes - downvotes) / threshold`
- [x] On hover: display a tooltip that indicates the threshold (see zeplin above)
## Coding Guidelines
- [x] The gradient of the progress bar should be implemented in the theme

**Comment by Aharon-Porath** [comment]
@avirankatz Please notices that the tooltip on hover should display number of "for" votes  (=upvotes) needed for approval, i.e.: `threshold - upvotes + downvotes. `
