### ISSUE TITLE
Bug: type script code displayed on frontend

### ISSUE THREAD

**Issue by Aharon-Porath** [consenz-io/webapp#186]
On agreement page, sections text shown with code tags. See screenshot -  

![image](https://user-images.githubusercontent.com/5900841/195087714-f953b894-6468-4c7e-b114-983e56e0230f.png)

**Comment by avirankatz** [comment]
@Aharon-Porath 
This is part of transitioning to markdown as discussed in the previous sprint.
Instead of parsing json, the editor is going to parse markdown and apply its styling. This should result in lighter data transfers over the network.

**Comment by Aharon-Porath** [comment]
I see. ok
