### ISSUE TITLE
🧱 Delete Permissions for versions, comments

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#226]
## DOD:
- [x] Allow a user delete a section version that they're the author of
- [x] Allow a moderator to delete a section version in any of their groups
- [x] Allow a user to delete a comment that they're the author of
- [x] Allow a moderator to delete a comment in any of their groups

**Comment by Aharon-Porath** [comment]
@avirankatz Should be applied on all content - sew section suggestion, new version suggestion, new comment.
