### ISSUE TITLE
🐞 [UI] The "All Agreements" icon the the sidebar is not as designed

### ISSUE THREAD

**Issue by tzur-sofi** [consenz-io/webapp#298]
<img width="85" alt="image" src="https://user-images.githubusercontent.com/93704857/207617676-03098f7e-3398-4820-a8a3-eb5bed29288b.png">

Its the copy icon i think,
was it a problem to implement the one in the design?

i.e:
<img width="116" alt="image" src="https://user-images.githubusercontent.com/93704857/207617830-83c1b720-6394-4a76-8d88-08a76c6c9ab1.png">

**Comment by avirankatz** [comment]
@tzur-sofi I'm on it

**Comment by avirankatz** [comment]
@tzur-sofi could you check again? You may change the status from [project](https://github.com/orgs/consenz-io/projects/1/views/2) screen
