### ISSUE TITLE
🐛  Can not delete a group on backoffice

### ISSUE THREAD

**Issue by Aharon-Porath** [consenz-io/webapp#307]
Trying to delete a group on retool give this error log:
{"status":400,"message":"permission denied for table groups","error":true,"queryExecutionMetadata":{"estimatedResponseSizeBytes":61,"resourceTimeTakenMs":1105,"isPreview":false,"resourceType":"postgresql","lastReceivedFromResourceAt":1671625142714...

**Comment by avirankatz** [comment]
@Aharon-Porath fixed. Please note that the group must be empty (no users nor agreements

**Comment by Aharon-Porath** [comment]
@avirankatz We most have a way to get a list of all users of a group and to manage them (in backoffice as a start, later on UI). Now admin can see users-groups relations only on the user data in backoffice, which make it very difficult to manage groups

**Comment by avirankatz** [comment]
@Aharon-Porath closing for now
