### ISSUE TITLE
Agreement categories table

### ISSUE THREAD

**Issue by Noafinkelstein** [consenz-io/webapp#57]
## DOD:
Categories table in hasura.
- [x] Validate with Tzur that we're dealing with one to many relations
- [x] Each category should contain a group (one to many), required
- [x] Each agreement should contain a category (one to many), optional

**Comment by yishain11** [comment]
Q:
**Each category should contain a group (one to many), required** = if the connection is a category has at least 1 group, how to model it? If I understand correctly, I would think to have a categories table with name and ID, and in the GROUPS table to have a category column. not the other way around.
