### ISSUE TITLE
🧱  Suggestions table in db

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#88]
## DOD:
- [x] Add a suggestions table to the db with the columns: id, updated_at, created_at, section_id (relation), content
- [x] Permissions: only users that are part of the relevant group (suggestion ➡️ section➡️ document➡️ group) are to be allowed to view a suggestion.
- [x] Permissions (2): users can create suggestions for sections only if the section is a"descendant" of one of their groups

**Comment by Aharon-Porath** [comment]
> Permissions: only users that are part of the relevant group (suggestion ➡️ section➡️ document➡️ group) are to be allowed to view a suggestion.

Is it necessary? We want to allow unregistered users to brows the agreements and discussions. Registration to the group should be a condition for interacting with suggestion - vote, comment, add improvement suggestion, not for viewing. 

@avirankatz

**Comment by avirankatz** [comment]
> > Permissions: only users that are part of the relevant group (suggestion ➡️ section➡️ document➡️ group) are to be allowed to view a suggestion.
> 
> Is it necessary? We want to allow unregistered users to brows the agreements and discussions. Registration to the group should be a condition for interacting with suggestion - vote, comment, add improvement suggestion, not for viewing.
> 
> @avirankatz

This would require ux/ui design, as we would need to consider what buttons are to be disabled/hidden when a public user views a group, an agreement, a section, a suggestion, categories etc.

**Comment by Aharon-Porath** [comment]
> This would require ux/ui design, as we would need to consider what buttons are to be disabled/hidden when a public user views a group, an agreement, a section, a suggestion, categories etc.

As I see it, all pages and all components should be visible to all users, logged in or not, part of the relevant group or not.

User that is logged in that tries to interacted with those buttons/actions mentioned below should be redirected to the login page.  
After completing the login process, the user should be redirected to the last page they visits, and will be allowed now to complete the action.

A logged in user that is not part of the relevant group will be added to the group automatically when interacting with it by making one of those actions. (Closed groups will be a added as a premium feature in the future.)  

The actions are: 
1. Group page:

**Comment by biwashingtonial** [comment]
@avirankatz Shouldn't a user_id column be included as well, to identify which user entered the suggestion?

**Comment by biwashingtonial** [comment]
Ready to QA (without the user_id column mentioned above): https://github.com/consenz-io/webapp/pull/95
