### ISSUE TITLE
Change auth0 password requirements 

### ISSUE THREAD

**Issue by Aharon-Porath** [consenz-io/webapp#90]
To make new users onboarding easier, remove new password restrictions such as: 

A password must contain:

- At least 8 characters
- At least 3 of the following:
- Lower case letters (a-z)
- Upper case letters (A-Z)
- Numbers (0-9)
- Special characters (ex. !@#$%^&*)

**Comment by avirankatz** [comment]
@Aharon-Porath Done. This is the current policy, how does this look to you?
<img width="491" alt="image" src="https://user-images.githubusercontent.com/11233754/180972286-4ae8834e-c858-4c8e-8a7b-3f07f0ebdb75.png">

Closing this issue for now. Feel free to reopen if you need anything else.

**Comment by Aharon-Porath** [comment]
> @Aharon-Porath Done. This is the current policy, how does this look to you? <img alt="image" width="491" src="https://user-images.githubusercontent.com/11233754/180972286-4ae8834e-c858-4c8e-8a7b-3f07f0ebdb75.png">
> 
> Closing this issue for now. Feel free to reopen if you need anything else.

This is fine.
