### ISSUE TITLE
Add appbar to agreement creation

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#96]
[zeplin](https://app.zeplin.io/project/629dca51967eeb127721428d/screen/62cc351f360cfc109d8da3ae)

## DOD:
- [x] Add an appbar with same background/transparent background and a divider to agreement creation flow
- [x] Add the agreement's name on the left side
- [x] Add a stepper and display the current step in the middle
- [x] add a close button on the right side

**Comment by yishain11** [comment]
is there figma for this?
