### ISSUE TITLE
🧱 Preliminary Agreement Screen

### ISSUE THREAD

**Issue by avirankatz** [consenz-io/webapp#99]
See [design](https://www.figma.com/file/oTbgKEXP9kTSbSWsfOnGwp/Consenz-Wireframe?node-id=1692%3A8173).
zeplin: [zeplin](https://app.zeplin.io/project/629dca51967eeb127721428d/screen/62e93ecc51114315b4702715)
For now, agreement details may be stubs. We're going to write an agreement context in a separate issue.
## DOD:
- [x] App bar with breadcrumbs (category > agreement name)
- [x] Header - agreement name
- [x] Rationale
- [x] Load that screen when navigating to `/:groupSlug/agreement/:agreementId`

**Comment by yishain11** [comment]
need to create new componnet for agreement view
